    SELECT EST.NOMBRE_ESTUDIANTE AS ESTUDIANTE, MAX(CAL.CALIFICACION) AS CALIFICACION_MAXIMA
      FROM SYSTEM.ESTUDIANTES EST
INNER JOIN SYSTEM.CALIFICACIONES CAL
        ON EST.ID_ESTUDIANTE = CAL.ID_ESTUDIANTE
  GROUP BY EST.NOMBRE_ESTUDIANTE
  ORDER BY EST.NOMBRE_ESTUDIANTE;

/*
ESTUDIANTE      CALIFICACION_MAXIMA
----------------------------------
ADRIANA SALAS	  85
DANIEL NAVA	      95
DANIELA PEREZ	  65
ISRAEL MARTINEZ	  75
JESUS HERNANDEZ	  75
JIMENA CASTRO	  70
JORGE VELEZ	      60
JUAN PEREZ	      90
JUANA RAMOS	      85
KARLA LOPEZ	      75
KATIA JIMENEZ	  90
MANUEL GONZALEZ	  85.5
RICARDO FLORES	  95
ROSA HUERTA	      90
TERESA HURTADO	  99

*/