 CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE     NUMBER(3) PRIMARY KEY,
    NOMBRE_ESTUDIANTE VARCHAR2(25)
 );
 
  CREATE TABLE PROFESORES (
    ID_PROFESOR     NUMBER(3) PRIMARY KEY,
    NOMBRE_PROFESOR VARCHAR2(25)
 );
 
  CREATE TABLE CURSOS (
    CLAVE_CURSO     NUMBER(3) PRIMARY KEY,
    NOMBRE_CURSO    VARCHAR2(20),
    HORARIO_CURSO   VARCHAR2(20),
    AULA_CURSO      VARCHAR2(10),
    ID_PROFESOR     NUMBER(3),

    CONSTRAINT FK_ID_PROF FOREIGN KEY (ID_PROFESOR)
    REFERENCES PROFESORES(ID_PROFESOR)
 );
 
 
  CREATE TABLE CALIFICACIONES (
    CLAVE_CURSO     NUMBER(3),
    ID_PROFESOR     NUMBER(3),
    ID_ESTUDIANTE   NUMBER(3),
    CALIFICACION    NUMBER(3,1),
    
    CONSTRAINT FK_CLAVCUR FOREIGN KEY (CLAVE_CURSO)
    REFERENCES CURSOS(CLAVE_CURSO),
    
    CONSTRAINT FK_IDPROF FOREIGN KEY (ID_PROFESOR)
    REFERENCES PROFESORES(ID_PROFESOR),
    
    CONSTRAINT FK_IDESTUD FOREIGN KEY (ID_ESTUDIANTE)
    REFERENCES ESTUDIANTES(ID_ESTUDIANTE)
 );