    SELECT CUR.NOMBRE_CURSO AS CURSO, EST.NOMBRE_ESTUDIANTE AS ESTUDIANTE
      FROM SYSTEM.ESTUDIANTES EST
INNER JOIN SYSTEM.CALIFICACIONES CAL
        ON EST.ID_ESTUDIANTE = CAL.ID_ESTUDIANTE
INNER JOIN SYSTEM.CURSOS CUR
        ON CAL.CLAVE_CURSO = CUR.CLAVE_CURSO
       AND CAL.ID_PROFESOR = CUR.ID_PROFESOR
  ORDER BY CUR.NOMBRE_CURSO;
  
/*
CURSO          ESTUDIANTE
------------------------------
BIOLOGIA	   DANIEL NAVA
BIOLOGIA	   JUANA RAMOS
BIOLOGIA	   KARLA LOPEZ
BIOLOGIA	   JIMENA CASTRO
BIOLOGIA	   ISRAEL MARTINEZ
BIOLOGIA	   RICARDO FLORES
BIOLOGIA	   KATIA JIMENEZ
BIOLOGIA	   DANIELA PEREZ
BIOLOGIA	   ADRIANA SALAS
BIOLOGIA	   ROSA HUERTA
FISICA	       MANUEL GONZALEZ
FISICA	       JUAN PEREZ
FISICA	       JORGE VELEZ
FISICA	       KATIA JIMENEZ
FISICA	       TERESA HURTADO
FISICA	       DANIELA PEREZ
FISICA	       JESUS HERNANDEZ
GEOGRAFIA	   RICARDO FLORES
GEOGRAFIA	   ISRAEL MARTINEZ
GEOGRAFIA	   JIMENA CASTRO
GEOGRAFIA	   JUANA RAMOS
GEOGRAFIA	   DANIELA PEREZ
HISTORIA	   MANUEL GONZALEZ
HISTORIA	   KATIA JIMENEZ
HISTORIA	   DANIEL NAVA
HISTORIA	   JORGE VELEZ
HISTORIA	   JUANA RAMOS
HISTORIA	   JUAN PEREZ
HISTORIA	   RICARDO FLORES
HISTORIA	   JIMENA CASTRO
INFORMATICA	   TERESA HURTADO
INFORMATICA	   ROSA HUERTA
LECTURA	       KARLA LOPEZ
LECTURA	       JESUS HERNANDEZ
LECTURA	       ADRIANA SALAS
LECTURA	       ISRAEL MARTINEZ
MATEMATICAS	   JESUS HERNANDEZ
MATEMATICAS	   JORGE VELEZ
MATEMATICAS	   ROSA HUERTA
MATEMATICAS	   JUAN PEREZ
MATEMATICAS	   DANIEL NAVA
MATEMATICAS	   ADRIANA SALAS
MATEMATICAS	   KARLA LOPEZ

*/