    SELECT PRO.NOMBRE_PROFESOR AS PROFESOR,  AVG(CAL.CALIFICACION) AS PROMEDIO
      FROM SYSTEM.PROFESORES PRO
INNER JOIN SYSTEM.CURSOS CUR
        ON PRO.ID_PROFESOR = CUR.ID_PROFESOR
INNER JOIN SYSTEM.CALIFICACIONES CAL
        ON CUR.CLAVE_CURSO = CAL.CLAVE_CURSO
       AND CUR.ID_PROFESOR = CAL.ID_PROFESOR
  GROUP BY PRO.NOMBRE_PROFESOR
  ORDER BY PRO.NOMBRE_PROFESOR;
  
 /*
 
PROFESOR         PROMEDIO
----------------------------
DAMIAN ESTRADA	 74.6428571
JESUS CARRANZA	 55
JORGE LOPEZ	 63.1875
JOSEFA ORTIZ	 76.5
MARTHA ELIZALDE	 75.5833333
 
*/